system:
  data_dir: /home/oj/data
  temp_dir: /mnt/cwoj_tmp
  db_host: localhost
  db_user: root
  db_pass: 009414
  db_name: CDOJ
  http_bind_addr: 0.0.0.0
  http_bind_port: 8881
  ruc_path:

log:
  normal_log_file:
  exception_log_file:

languages:
  - id: 1
    file_extension: cpp
    extra_memory: 20480
    compilation_exec: g++ -static -std=c++03 -fno-asm -s -Wall -O2 -lm -DONLINE_JUDGE -o %1% %2%
  - id: 2
    file_extension: c
    extra_memory: 20480
    compilation_exec: gcc -static -std=c99 -fno-asm -s -Wall -O2 -lm -DONLINE_JUDGE -o %1% %2%
  - id: 3
    file_extension: pas
    extra_memory: 20480
    compilation_exec: fpc -Xs -Sgic -O2 -dONLINE_JUDGE -o %1% %2%
  - id: 4
    file_extension: cpp
    extra_memory: 20480
    compilation_exec: g++ -static -std=c++11 -s -Wall -O2 -lm -DONLINE_JUDGE -o %1% %2%
